--Basic
require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")

-- Plugins config
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.nvim-comment")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.conform")
require("plugins.nvim-lint")
